#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        O -1.3058409 -1.45366652 0.05170258 region=Water_D
        H -1.46201979 -0.49778614 -0.06684584 region=Water_D
        H -1.7206005 -1.68178323 0.88324146 region=Water_D
    End
    Symmetrize Yes
    BondOrders
         1 2 0.8201484084129333
         1 3 0.8876383900642395
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        GGA BLYP
        DISPERSION GRIMME3 BJDAMP
    End
    Title Water_D fragment
    NumericalQuality Good
EndEngine
eor

