#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        O 1.45366652 -1.3058409 -0.05170258 region=Water_A
        H 1.68178323 -1.7206005 -0.88324146 region=Water_A
        H 0.49778614 -1.46201979 0.06684584 region=Water_A
    End
    Symmetrize Yes
    BondOrders
         1 2 0.8877494335174561
         1 3 0.8198812007904053
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        GGA BLYP
        DISPERSION GRIMME3 BJDAMP
    End
    Title Water_A fragment
    NumericalQuality Good
EndEngine
eor

