#!/bin/sh

# dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing/DonorAcceptor/NH3BH3.BH3 NH3BH3.BH3.results/adf.rkf BH3.rkf
# dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing/DonorAcceptor/NH3BH3.NH3 NH3BH3.NH3.results/adf.rkf NH3.rkf

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        B 0.0 0.0 0.861897 region=BH3 adf.f=BH3
        H -0.585967 1.014925 1.168784 region=BH3 adf.f=BH3
        H -0.585967 -1.014925 1.168784 region=BH3 adf.f=BH3
        H 1.171934 0.0 1.168784 region=BH3 adf.f=BH3
        N 0.0 0.0 -0.815297 region=NH3 adf.f=NH3
        H 0.477057 -0.826287 -1.184317 region=NH3 adf.f=NH3
        H -0.954115 0.0 -1.184317 region=NH3 adf.f=NH3
        H 0.477057 0.826287 -1.184317 region=NH3 adf.f=NH3
    End
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
         5 6 1.0
         5 7 1.0
         5 8 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    Fragments
        BH3 BH3.rkf 
        NH3 NH3.rkf 
    End
    
    XC
        GGA BLYP
    End
    NumericalQuality VeryGood
EndEngine
eor

