#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        N 0.0 0.0 -0.815297 region=NH3
        H 0.477057 -0.826287 -1.184317 region=NH3
        H -0.954115 0.0 -1.184317 region=NH3
        H 0.477057 0.826287 -1.184317 region=NH3
    End
    Symmetrize Yes
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title NH3 fragment
    NumericalQuality VeryGood
EndEngine
eor

