#!/bin/sh

# dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing_2019/HeterolyticBond/NaCl.Cl NaCl.Cl.t21 Cl.t21
# dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing_2019/HeterolyticBond/NaCl.Na NaCl.Na.t21 Na.t21
"$ADFBIN/adf" <<eor
:: # dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing_2019/HeterolyticBond/NaCl.Cl NaCl.Cl.t21 Cl.t21
:: # dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing_2019/HeterolyticBond/NaCl.Na NaCl.Na.t21 Na.t21
    Atoms
    1 Na      -2.765851310000       0.659301770000      -0.000000000000  f=Na b=Na 
    2 Cl       0.081289010000       0.786941950000       0.000000000000  f=Cl b=Cl 
    End
    Basis
        Type TZ2P
        Core None
        CreateOutput None
    End
    Fragments
        Cl Cl.t21 
        Na Na.t21 
    end
    GUIBonds
        1 1 2 1.0
    End
    NoPrint LOGFILE
    XC
        GGA BLYP
    End
    Relativistic Scalar ZORA
    NumericalQuality VeryGood

eor


