#!/bin/sh

"$ADFBIN/adf" <<eor
    Atoms
    1 Na      -2.765851310000       0.659301770000      -0.000000000000    
    End
    Basis
        Type TZ2P
        Core None
        CreateOutput None
    End
    GUIBonds
    End
    NoPrint LOGFILE
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title Na fragment
    Relativistic Scalar ZORA
    Charge 1
    NumericalQuality VeryGood

eor


