import pyfmo
from scm import plams
from tcutility import timer, cache, ensure_list
import os
import numpy as np
from collections.abc import Container
from typing_extensions import deprecated



class Orbital:
    def __init__(self, data, parent):
        self.data = data
        for key, value in data.items():
            setattr(self, key, value)
        self.parent = parent

    def __repr__(self):
        return str(self)

    @property
    @cache.cache
    @timer.timer
    def relative_name(self):
        orbitals = [orb for orb in self.parent.orbitals if orb.spin == self.spin and orb.spin_total_occupation == self.spin_total_occupation]
        if hasattr(self, 'fragment_unique'):
            orbitals = [orb for orb in orbitals if orb.fragment_unique == self.fragment_unique]

        energies = sorted([orb.energy for orb in orbitals])
        order = energies.index(self.energy) + self.degeneracy_index

        if self.doubly_occupied:
            order = len(orbitals) - order - 1
            return f'HOMO-{order}' if order > 0 else 'HOMO'

        if self.singly_occupied:
            if self.occupation == 1:
                order = len(orbitals) - order - 1
                return f'SOMO-{order}' if order > 0 else 'SOMO'
            else:
                return f'SUMO+{order}' if order > 0 else 'SUMO'

        if self.unoccupied:
            return f'LUMO+{order}' if order > 0 else 'LUMO'

    @property
    @cache.cache
    @timer.timer
    def irrep_relative_name(self):
        orbitals = [orb for orb in self.parent.orbitals if orb.spin == self.spin and orb.spin_total_occupation == self.spin_total_occupation and orb.symmetry == self.symmetry]
        if hasattr(self, 'fragment_unique'):
            orbitals = [orb for orb in orbitals if orb.fragment_unique == self.fragment_unique]

        energies = sorted([orb.energy for orb in orbitals])
        order = energies.index(self.energy) + self.degeneracy_index

        if self.doubly_occupied:
            order = len(orbitals) - order - 1
            return f'HOMO-{order}' if order > 0 else 'HOMO'

        if self.singly_occupied:
            if self.occupation == 1:
                order = len(orbitals) - order - 1
                return f'SOMO-{order}' if order > 0 else 'SOMO'
            else:
                return f'SUMO+{order}' if order > 0 else 'SUMO'

        if self.unoccupied:
            return f'LUMO+{order}' if order > 0 else 'LUMO'

    @property
    def doubly_occupied(self):
        return self.spin_total_occupation == 2

    @property
    def singly_occupied(self):
        return self.spin_total_occupation == 1

    @property
    def unoccupied(self):
        return self.spin_total_occupation == 0

    @property
    @cache.cache
    @timer.timer
    def spin_total_occupation(self):
        matching_orbs = [orb for orb in self.parent.orbitals if orb.name == self.name]
        if hasattr(self, 'fragment_unique'):
            matching_orbs = [orb for orb in matching_orbs if orb.fragment_unique == self.fragment_unique]

        return sum(orb.occupation for orb in matching_orbs)

    def cube_file(self, gridsize: str = 'medium', overwrite: bool = False):
        '''
        Generate a cube-file for this SFO with a certain grid-size.

        Args:
            gridsize: the size of the grid to generate the cube-file with.
        '''
        from tcutility.job.adf import DensfJob
        from tcintegral import grid

        # start a Densf job to calculate the cube-file. 
        # We want to return the cube-file, so we should wait for it to finish.
        with DensfJob(wait_for_finish=True, overwrite=overwrite) as job:
            # job.orbital(self)
            if isinstance(self, SFO):
                job._sfos.append(self)
            else:
                job._mos.append(self)
            job.settings.ADFFile = self.parent.parent.kfpath
            job.gridsize(gridsize)

        # output_cub_paths returns a list of cube-files generated by the job.
        # we only generate one, so we simply return the first element
        return grid.from_cub_file(job.output_cub_paths[0])

    def draw(self, gridsize: str = 'medium', isovalue: float = 0.03, overwrite: bool = False, screen=None, transform=None):
        '''
        Generate and draw a cube-file for this SFO object.

        Args:
            gridsize: the size of the grid to generate the cube-file with.
            isovalue: the value with which to generate the isosurface of this SFO.

        .. seealso::
            :meth:`SFO.cube_file` to generate and return a cube-file for this SFO.
        '''
        import tcviewer

        # generate a cube-file or load an existing one
        cub = self.cube_file(gridsize=gridsize, overwrite=overwrite)

        if screen is None:
            scr = tcviewer.Screen()
            scr.__enter__()
            scr.window.show()
        else:
            scr = screen

        # and draw it with a specified isovalue
        with scr.add_molscene() as scene:
            c1, c2 = ([1, 0, 0], [0, 0, 1]) if self.occupied else ([1, .5, 0], [0, 1, 1])
            if transform is not None:
                scene.transform = transform.to_vtkTransform()

            scene.draw_molecule(self.molecule)
            scene.draw_isosurface(cub, -0.03, c1)
            scene.draw_isosurface(cub,  0.03, c2)
            # scene.draw_axes()

        if screen is None:
            scr.exec()

        return scr

    @property
    def degeneracy_index(self):
        return self.degenerate_orbitals.index(self)

    @property
    def degenerate(self):
        return self.degeneracy > 1

    @property
    def degeneracy(self):
        return len(self.degenerate_orbitals)

    @property
    @cache.cache
    @timer.timer
    def degenerate_orbitals(self):
        return [orb for orb in self.parent.orbitals if orb.energy == self.energy]


class MO(Orbital):
    def __str__(self):
        if self.spin == 'AB':
            return f'{self.name}'
        return f'{self.name}_{self.spin}'


class SFO(Orbital):
    def __str__(self): 
        if self.spin == 'AB':
            return f'{self.fragment_unique}({self.name})'
        return f'{self.fragment_unique}({self.name})_{self.spin}'

    def overlap(self, other):
        assert isinstance(other, SFO)

        if self.spin != other.spin:
            return 0

        if self.symmetry != other.symmetry:
            return 0

        S = self.parent.parent.data.matrices.overlap[self.symmetry][self.spin]
        return S[other.symmetry_index][self.symmetry_index]


    def fock(self, other):
        assert isinstance(other, SFO)

        if self.spin != other.spin:
            return 0

        if self.symmetry != other.symmetry:
            return 0

        F = self.parent.parent.data.matrices.fock[self.symmetry][self.spin]
        return F[other.symmetry_index][self.symmetry_index]


    def mulliken_contribution(self, other):
        assert isinstance(other, MO)

        if self.spin != other.spin and other.spin != 'AB':
            return 0

        if self.symmetry != other.symmetry:
            return 0

        c = self.parent.parent.data.matrices.mulliken_contribution[self.symmetry][other.spin]
        return c[other.symmetry_index][self.symmetry_index]


    def coefficient(self, other):
        assert isinstance(other, MO)

        if self.spin != other.spin and other.spin != 'AB' and self.spin != 'AB':
            return 0

        if self.symmetry != other.symmetry:
            return 0

        c = self.parent.parent.data.matrices.coefficients[self.symmetry][other.spin]
        return c[other.symmetry_index][self.symmetry_index]


    def __matmul__(self, other):
        return self.overlap(other)


    def make_name(self, spin=True, frag_name=False, relative_name=False, index_name=False):
        name = ''

        if frag_name:
            name += self.fragment_unique + '('

        if relative_name:
            name += self.relative_name
        elif index_name:
            name += str(self.index) + self.symmetry
        else:
            name += self.name

        if frag_name:
            name += ')'

        if self.spin != 'AB' and spin:
            name += f'_{self.spin}'

        return name


class Orbitals:
    '''
    Container class that stores information about both MO's and SFO's.
    '''
    def __init__(self, path: str, path_SCF0: str = None, path_fragments: dict[str] = None, moleculename: str = None, path_output: str = None):
        r'''
        Two kind of readers are constucted.
        1. path provides the path to a fully converged Fragment analyses calculation with a full SCF. From this, all 
            information regarding the fragment analysis is extracted. This includes the SFO energies of the fully isolated 
            fragments and, if available, the site energies or Fock matrix. From this can return the site energies (diagonal 
            of the Fock matrix).

            The energies taken from this file are the SFO energies of the fully isolated fragments and the site energies 
            (diagonal of the Fock matrix) of the fully relaxed complex.

        2. The path_SCF0 is the pathway to the fragment analysis where SCF is set to zero (SCF=0). This is necessary for 
            reading the site energies (diagonal of the Fock matrix) to obtain the corrected energies of the SFOs. No other 
            information is read from this file.

            The energies extracted from this file are the site energies (diagonal of the Fock matrix) of the two fragments 
            in the field of the second respective fragment. This correction is often considered superior to the SFO energies 
            for the fully isolated fragments.
        '''
        self.reader = plams.KFReader(path)
        self.kfpath = os.path.abspath(path)
        self.SCF0_kfpath = path_SCF0
        self.SCF0_reader = plams.KFReader(path_SCF0) if path_SCF0 else None

        self.fragment_kfpaths = path_fragments
        if self.fragment_kfpaths:
            self.fragment_orbs = {frag: Orbitals(fpath) for frag, fpath in path_fragments.items()}
        else:
            self.fragment_orbs = {}

        self.output = os.path.abspath(path_output) if path_output else None
        with timer.timer('Orbitals.get_data'):
            self.get_data()
        with timer.timer('Orbitals.gather_sfos'):
            self.gather_sfos()
        with timer.timer('Orbitals.gather_mos'):
            self.gather_mos()

    def get_data(self):
        self.data = pyfmo.orbitals2.adf._read_data(self.reader, SCF0_reader=self.SCF0_reader, output=self.output)

    def gather_sfos(self):
        self.sfos = SFOs([], self)
        sfo_mo_spin_match = self.data.calc_info.unrestricted_mos == self.data.calc_info.unrestricted_sfos
        for sfo_idx in range(self.data.SFOs.number):
            for spin_idx, sfo_spin in enumerate(self.data.calc_info.sfo_spins):
                if not sfo_mo_spin_match:
                    if self.data.calc_info.unrestricted_mos:
                        gross_pop = self.data.SFOs.gross_population.A[sfo_idx] + self.data.SFOs.gross_population.B[sfo_idx]
                        gross_spin = self.data.SFOs.gross_population.A[sfo_idx] - self.data.SFOs.gross_population.B[sfo_idx]
                    else:
                        gross_pop = self.data.SFOs.gross_population.AB[sfo_idx]
                        gross_spin = 0
                else:
                    gross_pop = self.data.SFOs.gross_population[sfo_spin][sfo_idx]
                    gross_spin = 0

                data = {
                    'index': sfo_idx + 1,
                    'name': self.data.SFOs.adf_names[sfo_spin][sfo_idx],
                    'subspecies': self.data.SFOs.subspecies[sfo_idx],
                    'symmetry': self.data.SFOs.symlabel[sfo_idx],
                    'symmetry_index': self.data.SFOs.symmetry_index[sfo_idx],
                    'index_in_symlabel': self.data.SFOs.symmetry_index[sfo_idx], # rmove this later
                    'fragment': self.data.calc_info.fragments[self.data.SFOs.fragment_index[sfo_idx] - 1].split(':')[0],
                    'fragment_unique': self.data.SFOs.fragment_unique.total[sfo_idx],
                    'fragment_index': self.data.SFOs.fragment_index[sfo_idx],
                    'spin': sfo_spin,
                    'energy': self.data.SFOs.energy[sfo_spin][sfo_idx] * 27.2114079527,
                    'occupation': float(self.data.SFOs.occupation[sfo_spin][sfo_idx]),
                    'occupied': int(self.data.SFOs.occupation[sfo_spin][sfo_idx]) > 0,
                    'gross_population': gross_pop,
                    'gross_spin': gross_spin,
                    'molecule': self.data.SFOS.fragment_molecules[self.data.SFOs.fragment_unique.total[sfo_idx]],
                }

                data['site_energy'] = np.nan
                if isinstance(self.data.SFOs.site_energy[sfo_spin], np.ndarray):
                    data['site_energy'] = self.data.SFOs.site_energy[sfo_spin][sfo_idx] * 27.2114079527

                data['site_energy_SCF0'] = np.nan
                if isinstance(self.data.SFOs.site_energy_SCF0[sfo_spin], np.ndarray):
                    data['site_energy_SCF0'] = self.data.SFOs.site_energy_SCF0[sfo_spin][sfo_idx] * 27.2114079527

                sfo = SFO(data, self.sfos)
                self.sfos.orbitals.append(sfo)

    def gather_mos(self):
        self.mos = MOs([], self)
        for moi in range(self.data.SFOs.number):
            for spin_idx, mo_spin in enumerate(self.data.calc_info.mo_spins):
                symm_idx = self.data.MOs.symmetry_index[moi]
                symlabel = self.data.MOs.symlabel[moi]
                occ = int(self.data.MOs.occupation[symlabel][mo_spin][symm_idx])
                if self.data.MOs.kinetic_energy:
                    kin = self.data.MOs.kinetic_energy[symlabel][symm_idx] * 27.2114079527 if occ else 0
                else:
                    kin = None

                data = {
                    'index': moi + 1,
                    'name': f'{symm_idx+1}{symlabel}',
                    'symmetry': symlabel,
                    'symmetry_index': self.data.MOs.symmetry_index[moi],
                    'index_in_symlabel': self.data.MOs.symmetry_index[moi], # rmove this later
                    'spin': mo_spin,
                    'energy': self.data.MOs.energy[symlabel][mo_spin][symm_idx] * 27.2114079527,
                    'occupation': occ,
                    'occupied': int(self.data.MOs.occupation[symlabel][mo_spin][symm_idx]) > 0,
                    'kinetic_energy': kin
                }
                sfo = MO(data, self.mos)
                self.mos.orbitals.append(sfo)

    @property
    def molecule(self):
        mol = plams.Molecule()
        for frag in self.fragments:
            sfo = [sfo for sfo in self.sfos if sfo.fragment_unique == frag][0]
            mol += sfo.molecule
        return mol

    @property
    def fragments(self):
        return self.sfos.fragments

    def write_excel(self, out_file: str = 'pyfmo.xlsx'):
        from pyfmo import write_excel
        
        write_excel.to_excel(self, out_file)

    def write_excel2(self, out_file: str = None):
        from pyfmo import write_excel2

        if out_file is None:
            out_file = os.path.join(os.path.dirname(self.kfpath), 'pyfmo2.xlsx')
        write_excel2.to_excel(self, out_file)

    def _get_mask(self, objs):
        if isinstance(objs[0], MO):
            return np.array([ref in objs for ref in self.mos.orbitals])
        return np.array([ref in objs for ref in self.sfos.orbitals])

    def overlap_matrix(self, sfos1, sfos2):
        mask1 = self._get_mask(sfos1)
        mask2 = self._get_mask(sfos2)
        Stotal = self.data.matrices.overlap.total
        return Stotal[:, mask1][mask2, :]

    @property
    def sfo_energy_types(self):
        return self.sfos.energy_types


class OrbitalSelector:
    '''
    Class used to select MOs or SFOs. 
    It is responsible for decoding selection keys and filtering orbitals based on the selection key.

    Args:
        orbitals: a list of SFOs or MOs that will be managed by this class.
        parent: the parent ``Orbitals`` object.
    '''
    def __init__(self, orbitals: Container[Orbital], parent: Orbitals):
        self.orbitals = orbitals
        self.parent = parent

    def __getitem__(self, key: int or str) -> list[Orbital] or Orbital:
        return self.get(key)

    def get(self, key: int or str) -> list[Orbital] or Orbital:
        '''
        Get ``Orbital`` objects based on the given key.

        Args:
            key: a string describing the orbital to be selected or the integer index of the orbital.

        Returns:
            A list of ``Orbital`` objects that match the given key.
            If there is only one return a single ``Orbital`` object.

        Examples:
            Select the HOMO of the NH3 fragment.

            .. code-block::

                >>> SFOs.get('NH3(HOMO)')
                NH3(3A1)
                >>> SFOs['NH3(HOMO)']
                NH3(3A1)


        .. seealso::

            :func:`~OrbitalSelector.filter` and :func:`~OrbitalSelector.decode_key`.

        .. note::

            The ``__getitem__`` method of this class redirects to this method, 
            allowing you to use indexing notation to obtain orbitals.
        '''
        return self.filter(**self.decode_key(key))

    def decode_key(self, key: str) -> dict:
        '''
        Decode a key into the relevant parts.
        Keys are given in the following format:

            {fragname}[:{fragment_index}]({orbname}[_{spin}][ {symmetry}])

        Where [:fragment_index], [_{spin}], and [ {symmetry}] are optional.

        If an SFO is desired you must begin the key with the fragment name
        and put the rest of the key within parentheses.

        Returns:
            A dictionary containing ``index``,  ``fragment``,
            ``fragment_index``, ``orbname``, ``spin``, ``symmetry``.

        Examples:
            Decode a key specifying an MO.

            .. code-block::

                >>> MOs.decode_key('4A1')
                {'orbname': '4A1'}
            
            One can also use relative naming. Also specify alpha spin.
            .. code-block::

                >>> MOs.decode_key('HOMO-2_A')
                {'orbname': 'HOMO-2', 'spin': 'A'}

            Decode a key for an SFO specifying the fragment, orbname and spin.
            .. code-block::

                >>> SFOs.decode_key('NH3(1E1:1_B)')
                {'fragment': 'NH3', 'orbname': '1E1:1_B'}
    
            If multiple fragments have the same name (e.g. in a non-fragment analysis with atomic fragments)
            we can specify the fragment index with the colon.
            .. code-block::

                >>> SFOs.decode_key('C:4(1P:x)')
                {'fragment': 'C', 'fragment_index': 4, 'orbname': '1P:x'}
        '''
        decoded = {
            'index': None,
            'fragment': None,
            'fragment_index': None,
            'orbname': None,
            'spin': None,
            'symmetry': None,
        }

        # if a single integer is given return only the index
        if isinstance(key, int):
            decoded['index'] = key
            return decoded

        # get spin from the key
        decoded['orbname'] = key
        for spin_part in ['_A', '_B', '_AB']:
            # extract both spin and orbname here
            if key.endswith(spin_part):
                decoded['spin'] = spin_part[1:]
                decoded['orbname'] = key[:-len(spin_part)]

        # split orbname into fragment name and orbname 
        if '(' in decoded['orbname']:
            decoded['fragment'], decoded['orbname'] = decoded['orbname'].split('(')
            decoded['orbname'] = decoded['orbname'].strip(')')

        # split off the symmetry of the orbital
        if ' ' in decoded['orbname']:
            decoded['orbname'], decoded['symmetry'] = decoded['orbname'].split()

        # extract fragment index from fragment name if present
        if decoded['fragment'] is not None and ':' in decoded['fragment']:
            decoded['fragment'], decoded['fragment_index'] = decoded['fragment'].split(':')
            decoded['fragment_index'] = int(decoded['fragment_index'])
        
        return {k: v for k, v in decoded.items() if v is not None}


    def filter(self, 
            index: int or Container[int] = None, 
            symmetry: str or Container[str] = None, 
            spin: str or Container[str] = None, 
            fragment: str or Container[str] = None, 
            fragment_index: int or Container[str]= None, 
            orbname: str or Container[str]= None) -> Orbital or list[Orbital]:
        '''
        filter ``Orbital`` objects that match the given parameters.
        If any of the arguments is given as a ``Container`` we check for membership.

        Arguments:
            index: the index of the orbital.
            symmetry: the symmetry label of the orbital.
            spin: the spin label of the orbital, should be one of [``A``, ``B``, ``AB``].
            fragment: the fragment name of the SFO.
            fragment_index: the index of the fragment of the SFO.
            orbname: the name of the orbital. Can be either the proper name or a relative name, e.g. ``SOMO`` or ``LUMO+5``.
        
        Returns:
            The ``Orbital`` objects that match the provided arguments.
            If there is only one ``Orbital`` object selected, return only that one.
            Otherwise return a ``list`` of ``Orbital`` objects.
            Returns ``None`` if no matching ``Orbital`` objects were found.

        Examples:
            Select all SFOs of a given fragment.

            .. code-block::

                >>> SFOs.filter(fragment='NH3')
                [NH3(1A1), NH3(2A1), NH3(3A1), ...]

            Select all SFOs from the A2 irrep of the BH3 fragment.

            .. code-block::

                >>> SFOs.filter(symmetry='A2', fragment='BH3')
                [BH3(1A2), BH3(2A2), BH3(3A2), BH3(4A2)]

            Select all MOs that are named '1E1:1' or '1E1:2'.

            .. code-block::

                >>> MOs.filter(orbname=('1E1:1', '1E1:2'))
                [1E1:1, 1E1:2]

            Select the HOMO of the NH3 fragment.

            .. code-block::

                >>> SFOs.filter(orbname='HOMO', fragment='NH3')
                NH3(3A1)

            Get 1P orbitals for all carbons

            .. code-block::

                >>> SFOs.filter(orbname=('1P:x', '1P:y', '1P:z'), fragment='C')
                [C:1(1P:x), C:1(1P:y), C:1(1P:z), C:2(1P:x), C:2(1P:y), C:2(1P:z), C:3(1P:x), C:3(1P:y), C:3(1P:z), C:4(1P:x), C:4(1P:y), C:4(1P:z)]
        
            Get 1P orbitals for the second carbon

            .. code-block::

                >>> SFOs.filter(orbname=('1P:x', '1P:y', '1P:z'), fragment='C:2')
                [C:2(1P:x), C:2(1P:y), C:2(1P:z)]
                >>> SFOs.filter(orbname=('1P:x', '1P:y', '1P:z'), fragment='C', fragment_index=2)
                [C:2(1P:x), C:2(1P:y), C:2(1P:z)]
        '''
        orbs = self.orbitals
        # filter down the orbitals in this object
        if index:
            orbs = [orb for orb in orbs if orb.index in ensure_list(index)]

        if symmetry:
            if self.parent.data.calc_info.used_regions:
                orbs = [orb for orb in orbs if orb.symmetry in ensure_list(symmetry)]
            else:
                orbs = [orb for orb in orbs if orb.subspecies in ensure_list(symmetry)]

        if spin:
            orbs = [orb for orb in orbs if orb.spin in ensure_list(spin)]

        # we match based on either fragment or fragment_unique
        # this ensures that if we select for instance "C(1P:x)" we match ALL carbons
        # if we match "C:1(1P:x)" we match only the first carbon
        if fragment:
            orbs = [orb for orb in orbs if orb.fragment_unique in ensure_list(fragment) or orb.fragment in ensure_list(fragment)]

        if fragment_index:
            orbs = [orb for orb in orbs if orb.fragment_index in ensure_list(fragment_index)]

        # orbname can be either the proper name or the relative name
        if orbname:
            orbs = [orb for orb in orbs if orb.name in ensure_list(orbname) or orb.relative_name in ensure_list(orbname)]

        # return None if nothing was found
        if len(orbs) == 0:
            return None

        # squeeze the list if only one element exists
        if len(orbs) == 1:
            return orbs[0]

        return orbs

    def __len__(self):
        return len(self.orbitals)

    def __iter__(self):
        return iter(self.orbitals)

    @property
    def spins(self) -> list[str]:
        '''
        The spin species that are present in the given orbitals.
        '''
        return list(sorted({orb.spin for orb in self.orbitals}))

    @property
    def unrestricted(self) -> bool:
        '''
        Whether the calculation was performed in an unrestricted manner.
        '''
        return all(orb.spin in ['A', 'B'] for orb in self.orbitals)


class SFOs(OrbitalSelector):
    @property
    def fragments(self) -> list[str]:
        '''
        Return a list of fragment names found in the orbitals.
        '''
        frags = []
        for sfo in self.orbitals:
            if sfo.fragment_unique not in frags:
                frags.append(sfo.fragment_unique)
        return frags

    @deprecated('SFOs.get_fragment_sfos is deprecated. Please us the SFOs.filter(fragment=...) method.')
    def get_fragment_sfos(self, fragment: str)-> list[SFO]:
        '''
        Return all SFOs that belong to a given fragment.

        Args:
            fragment: the fragment or unique fragment name.

        Examples:
            # return all SFOs that belong to a carbon atom
            >>> sfos = orbs.sfos.get_fragment_sfos('C') 
            # return all SFOs that belong to carbon C:1
            >>> sfos = orbs.sfos.get_fragment_sfos('C:1')
            # return all SFOs that belong to a named fragment
            >>> sfos = orbs.sfos.get_fragment_sfos('Donor')
        '''
        return [sfo for sfo in self.orbitals if sfo.fragment_unique == fragment or sfo.fragment == fragment]

    @property
    def energy_types(self):
        ret = []
        if len(self.orbitals) > 0:
            orb = self.orbitals[0]
            if orb.energy is not np.nan:
                ret.append('energy')
            if orb.site_energy is not np.nan:
                ret.append('site_energy')
            if orb.site_energy_SCF0 is not np.nan:
                print(orb.site_energy_SCF0)
                ret.append('site_energy_SCF0')

        return ret


class MOs(OrbitalSelector):
    ...



if __name__ == '__main__':
    orbs = Orbitals('/Users/yumanhordijk/PhD/Programs/TheoCheM/PyFMO/calculations/PyOrb_testing_2022/DonorAcceptor/NH3BH3.results/adf.rkf')

    # for sfo in orbs.sfos:
    #     print(sfo.fragment_unique)

    # print(orbs.data.mos.kinetic_energy)

    # for mo in orbs.mos:
    #     print(mo, mo.kinetic_energy)
    # orbs.write_excel2()

    sfos = orbs.sfos.filter(symmetry='A2', fragment='BH3')
    print(sfos)
    sfos = orbs.sfos.filter(fragment='NH3')
    print(sfos)
    sfos = orbs.sfos.get_fragment_sfos('NH3')
    print(sfos)
    sfos = orbs.mos.filter(orbname=('1E1:1', '1E1:2'))
    print(sfos)
    sfos = orbs.sfos.filter(orbname='HOMO', fragment='NH3')
    print(sfos)

    mo = orbs.sfos.get('NH3(HOMO)')
    print(mo)

    mo = orbs.sfos['NH3(HOMO)']
    print(mo)

    mo = orbs.sfos['NH3']
    print(mo)

    dk = orbs.mos.decode_key('HOMO-2_A')
    print(dk)


    dk = orbs.sfos.decode_key('NH3(1E1:1_B)')
    print(dk)


    dk = orbs.sfos.decode_key('C:4(1P:x)')
    print(dk)

    orbs = Orbitals('/Users/yumanhordijk/PhD/Programs/TheoCheM/PyFMO/calculations/PyOrb_testing_2022/TransitionState/DielsAlder.Diene.results/adf.rkf')
    print(orbs.sfos.filter(orbname=('1P:x', '1P:y', '1P:z'), fragment='C', fragment_index=2))
