#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 0.0 0.0 0.76576 region=Left
        H -0.51193035 0.88668938 1.16677 region=Left
        H 1.02386071 0.0 1.16677 region=Left
        H -0.51193035 -0.88668938 1.16677 region=Left
    End
    Symmetrize Yes
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    SpinPolarization 1
    XC
        GGA OLYP
    End
    Title Left fragment
    Unrestricted Yes
    NumericalQuality Good
EndEngine
eor

