[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true
template = "{tag}"
dev_template = "{tag}"
dirty_template = "{tag}"

[project]
name = "pyorbb"
# version = "%REPLACE_VERSION"
authors = [
  { name="Yuman Hordijk", email="y.hordijk@vu.nl"},
  { name="Steven E. Beutick", email="s.e.beutick@vu.nl"},
  { name="Xiaobo Sun"},
  { name="Laurens Groot"},
  { name="Tori Gijzen", email="t.gijzen@vu.nl"},
  { name="Jordi Poater"},
  { name="Trevor A. Hamlin", email="t.a.hamlin@vu.nl"},
  { name="F. Matthias Bickelhaupt", email="f.m.bickelhaupt@vu.nl"},
  { name="Célia Fonseca Guerra", email="c.fonsecaguerra@vu.nl"}]

description = "PyOrbb is an automated orbital analysis tool used in the TheoCheM group at VU Amsterdam"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"]

dynamic = ["version"]
dependencies = [
    "pyside6-essentials==6.7.3",
    "tcviewer==0.2",
    "tcmu==0.17.2",
    "numpy",
    "matplotlib>=3.5.3",
    "networkx>=2.6.3",
    "numpy>=1.21.6",
    "plams>=2024.106",
    "xlsxwriter>=3.2.2",
    "tcintegral>=1.0.3",
    "pyperclip",
    "platformdirs",
    "beautifulsoup4",
    "pyyaml",
    "ruff==0.0.177",
]

[project.optional-dependencies]
docs = [
    "gitpython>=3.1.45",
    "sphinx",
    "pydata-sphinx-theme>=0.13.3",
    "sphinx-argparse>=0.4.0",
    "sphinx-autodoc-typehints>=1.23.0",
    "sphinx-design>=0.4.1",
    "sphinx-tabs>=3.4.7",
    "sphinxcontrib-video>=0.4.1",
    # "sphinx_new_tab_link==0.8.1",
]

[project.scripts]
pyorbb = "pyorbb.cli_scripts.pyorbbparser:main"

# content below this line added by briefcase convert
# This project was generated with 0.3.25 using template: https://github.com/beeware/briefcase-template @ v0.3.25
[tool.briefcase]
project_name = "PyOrbb"
version= "%REPLACE_VERSION"
bundle = "nl.theochem"
url = "https://theochem.nl/pyorbb"
license.file = "LICENSE"
# author = "Yuman Hordijk, Xiaobo Sun, Steven E. Beutick, Laurens Groot, Tori Gijzen, Jordi Poater, Trevor A. Hamlin, Matthias Bickelhaupt, Célia Fonseca Guerra"
author = "TheoCheMVU"
author_email = "yumanhordijk@gmail.com"

[tool.briefcase.app.pyorbb]
formal_name = "PyOrbb"
description = "PyOrbb is an automated orbital analysis tool used in the TheoCheM group at VU Amsterdam"
long_description = """More details about the app should go here.
"""
icon = "icon_12"
sources = [
    "src/pyorbb",
]
requires = [
    ]
test_sources = [
    "test",
]

test_requires = [
    # Add your cross-platform test requirements here
]

[tool.briefcase.app.pyorbb.macOS]
universal_build = false
requires = [
]

[tool.briefcase.app.pyorbb.linux]
requires = [
    # Add your Linux-specific app requirements here
]

[tool.briefcase.app.pyorbb.linux.system.debian]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.pyorbb.linux.system.rhel]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.pyorbb.linux.system.suse]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.pyorbb.linux.system.arch]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.pyorbb.linux.flatpak]
flatpak_runtime = "org.freedesktop.Platform"
flatpak_runtime_version = "24.08"
flatpak_sdk = "org.freedesktop.Sdk"

[tool.briefcase.app.pyorbb.windows]
requires = [
    # Add your Windows-specific app requirements here
]

# Mobile deployments
[tool.briefcase.app.pyorbb.iOS]
requires = [
    # Add your iOS-specific app requirements here
]

[tool.briefcase.app.pyorbb.android]
requires = [
    # Add your Android-specific app requirements here
]

# Web deployments
[tool.briefcase.app.pyorbb.web]
requires = [
    # Add your web-specific app requirements here
]

