[project]
name = "pyfmo"
authors = [
  { name="Yuman Hordijk", email="y.hordijk@vu.nl"},
  { name="Steven E. Beutick", email="s.e.beutick@vu.nl"},
  { name="Tori Gijzen", email="t.gijzen@vu.nl"}]
description = "PyFMO is an automated orbital analysis tool used in the TheoCheM group at VU Amsterdam"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"]
dynamic = ["version"]
dependencies = [
    "matplotlib>=3.5.3",
    "networkx>=2.6.3",
    "numpy>=1.21.6",
    "plams>=2024.106",
    "xlsxwriter>=3.2.2",
]

[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true
template = "{tag}"
dev_template = "{tag}"
dirty_template = "{tag}"

[dependency-groups]
docs = [
    "gitpython>=3.1.45",
    "pydata-sphinx-theme>=0.13.3",
    "sphinx-argparse>=0.4.0",
    "sphinx-autodoc-typehints>=1.23.0",
    "sphinx-design>=0.4.1",
    "sphinx-tabs>=3.4.7",
    "sphinxcontrib-video>=0.4.1",
]

[project.scripts]
pyfmo = "pyfmo.cli_scripts.pyfmoparser:main"

[project.optional-dependencies]
draw = [
    "tcintegral>=1.0.0",
    "tcutility>=0.5.0",
    "tcviewer>=0.0.1",
]
