#!/bin/sh

# dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing/TransitionState/DielsAlder.Dienophile DielsAlder.Dienophile.results/adf.rkf Dienophile.rkf
# dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing/TransitionState/DielsAlder.Diene DielsAlder.Diene.results/adf.rkf Diene.rkf

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 2.64532 2.913587 0.08894299999999999 region=Dienophile adf.f=Dienophile
        C 3.696497 2.022919 0.228348 region=Dienophile adf.f=Dienophile
        H 2.413163 3.611832 0.891617 region=Dienophile adf.f=Dienophile
        H 2.305859 3.209255 -0.900564 region=Dienophile adf.f=Dienophile
        H 4.290078 2.019654 1.141232 region=Dienophile adf.f=Dienophile
        H 4.188822 1.614846 -0.650751 region=Dienophile adf.f=Dienophile
        C 0.810099 0.702461 -0.341801 region=Diene adf.f=Diene
        C 0.67866 1.813935 0.469122 region=Diene adf.f=Diene
        C 1.87838 -0.204138 -0.202961 region=Diene adf.f=Diene
        C 2.86272 -0.040256 0.753251 region=Diene adf.f=Diene
        H 0.195798 0.633908 -1.242208 region=Diene adf.f=Diene
        H -0.089657 2.557309 0.258078 region=Diene adf.f=Diene
        H 1.029715 1.795034 1.498 region=Diene adf.f=Diene
        H 2.038908 -0.930324 -1.002754 region=Diene adf.f=Diene
        H 3.736899 -0.690877 0.755494 region=Diene adf.f=Diene
        H 2.637146 0.430127 1.707202 region=Diene adf.f=Diene
    End
    BondOrders
         1 2 2.0
         1 3 1.0
         1 4 1.0
         2 5 1.0
         2 6 1.0
         7 8 2.0
         7 9 1.0
         7 11 1.0
         8 12 1.0
         8 13 1.0
         9 10 2.0
         9 14 1.0
         10 15 1.0
         10 16 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    Fragments
        Dienophile Dienophile.rkf 
        Diene Diene.rkf 
    End
    
    XC
        GGA BLYP
    End
    NumericalQuality VeryGood
EndEngine
eor

