#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        H 0.195798 0.633908 -1.242208 region=Diene
        H -0.089657 2.557309 0.258078 region=Diene
        H 1.029715 1.795034 1.498 region=Diene
        H 2.038908 -0.930324 -1.002754 region=Diene
        H 3.736899 -0.690877 0.755494 region=Diene
        H 2.637146 0.430127 1.707202 region=Diene
        C 0.810099 0.702461 -0.341801 region=Diene
        C 0.67866 1.813935 0.469122 region=Diene
        C 1.87838 -0.204138 -0.202961 region=Diene
        C 2.86272 -0.040256 0.753251 region=Diene
    End
    Symmetrize Yes
    BondOrders
         7 1 1.0
         7 8 2.0
         7 9 1.0
         8 2 1.0
         8 3 1.0
         9 4 1.0
         9 10 2.0
         10 5 1.0
         10 6 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title Diene fragment
    NumericalQuality VeryGood
EndEngine
eor

