#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 2.64532 2.913587 0.08894299999999999 region=Dienophile
        C 3.696497 2.022919 0.228348 region=Dienophile
        H 2.413163 3.611832 0.891617 region=Dienophile
        H 2.305859 3.209255 -0.900564 region=Dienophile
        H 4.290078 2.019654 1.141232 region=Dienophile
        H 4.188822 1.614846 -0.650751 region=Dienophile
    End
    Symmetrize Yes
    BondOrders
         1 2 2.0
         1 3 1.0
         1 4 1.0
         2 5 1.0
         2 6 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title Dienophile fragment
    NumericalQuality VeryGood
EndEngine
eor

