#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 1.761672 0.052473 0.000415 region=FeCO4
        C -0.004125 1.546377 0.959736 region=FeCO4
        Fe -0.010158 0.052195 0.012724 region=FeCO4
        O -2.932253 0.050321 0.033974 region=FeCO4
        C -1.781978 0.051149 0.025521 region=FeCO4
        O -0.000246 2.519915 1.577453 region=FeCO4
        O 2.911951 0.052501 -0.007313 region=FeCO4
        O 0.000182 -2.536505 1.368079 region=FeCO4
        C -0.003861 -1.514965 0.833458 region=FeCO4
    End
    Symmetrize Yes
    BondOrders
         3 1 1.0
         3 2 1.0
         3 5 1.0
         3 9 1.0
         4 5 2.0
         6 2 2.0
         7 1 2.0
         8 9 2.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title FeCO4 fragment
    NumericalQuality VeryGood
EndEngine
eor

