#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        O -0.030933 0.173098 -2.906776 region=CO
        C -0.022738 0.12546 -1.754801 region=CO
    End
    Symmetrize Yes
    BondOrders
         1 2 2.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title CO fragment
    NumericalQuality VeryGood
EndEngine
eor

