#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        N 0.0 0.0 -0.81397925 region=NH3
        H 0.4760389 -0.82452355 -1.14378691 region=NH3
        H -0.95207779 0.0 -1.14378691 region=NH3
        H 0.4760389 0.82452355 -1.14378691 region=NH3
    End
    Symmetrize Yes
    BondOrders
         1 2 0.9375154376029968
         1 3 0.9375330805778503
         1 4 0.9374578595161438
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        GGA OLYP
    End
    Title NH3 fragment
    NumericalQuality Good
EndEngine
eor

