#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        N -0.0 0.0 -0.814917 region=Donor
        H -0.95213416 0.0 -1.14409375 region=Donor
        H 0.47606708 -0.8245723700000001 -1.14409375 region=Donor
        H 0.47606708 0.8245723700000001 -1.14409375 region=Donor
    End
    Symmetrize Yes
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        GGA BLYP
    End
    Title Donor fragment
EndEngine
eor

