#!/bin/bash
#SBATCH -N 1
#SBATCH -t 100:00:00
#SBATCH --ntasks-per-node=32
#SBATCH --partition=tc
export SCM_TMPDIR=/scratch/${SLURM_JOBID}
srun mkdir -p $SCM_TMPDIR
chmod 700 $SCM_TMPDIR
cd $SCM_TMPDIR
export TC_SUBMISSION_DIR=$SLURM_SUBMIT_DIR

module list
module load ams/2021.102

srun mkdir -p $TMPDIR/$USER/$SLURM_JOBID
cd $TMPDIR/$USER/$SLURM_JOBID
echo $SLURM_SUBMIT_DIR > DIR


COMP="nh4"
MON1="nh3"
MON2="h"

AMS_JOBNAME=$MON1 $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/$MON1.out

Task SinglePoint

System
 Atoms
N      -0.00000000      -0.00000000      -0.00000000
H      -0.48583738      -0.84149503       0.34353891
H       0.97167477       0.00000000       0.34353891
H      -0.48583738       0.84149503       0.34353891
 End
Charge 0
End

Engine ADF
  BASIS
   type QZ4P
   core none
  END

  Print FMATSFO
  AllPoints Yes
  FullFock Yes

  Relativity
   level scalar
  End

  SYMMETRY C(3v)

  XC
    gga bp86
    DISPERSION Grimme3 BJDAMP
  END

  NumericalQuality excellent

EndEngine

END INPUT
eor

# Rename the output file.

cp $MON1.results/ams.rkf $SLURM_SUBMIT_DIR/$MON1.ams.rkf
cp $MON1.results/adf.rkf $SLURM_SUBMIT_DIR/$MON1.adf.rkf
cp $MON1.results/ams.log $SLURM_SUBMIT_DIR/$MON1.log


AMS_JOBNAME=$MON2 $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/$MON2.out

Task SinglePoint

System
 Atoms
H       0.00000000      -0.00000000      -1.03061673
 End
Charge 1
End

Engine ADF
  BASIS
   type QZ4P
   core none
  END

  Print FMATSFO
  AllPoints Yes
  FullFock Yes

  Relativity
   level scalar
  End

  SYMMETRY C(3v)

  XC
    gga bp86
    DISPERSION Grimme3 BJDAMP
  END

  NumericalQuality excellent

EndEngine

END INPUT
eor

# Rename the output file.

cp $MON2.results/ams.rkf $SLURM_SUBMIT_DIR/$MON2.ams.rkf
cp $MON2.results/adf.rkf $SLURM_SUBMIT_DIR/$MON2.adf.rkf
cp $MON2.results/ams.log $SLURM_SUBMIT_DIR/$MON2.log


AMS_JOBNAME=$COMP $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/$COMP.out

Task SinglePoint

System
 Atoms
N      -0.00000000      -0.00000000      -0.00000000 adf.f=nh3
H      -0.48583738      -0.84149503       0.34353891 adf.f=nh3
H       0.97167477       0.00000000       0.34353891 adf.f=nh3
H      -0.48583738       0.84149503       0.34353891 adf.f=nh3
H       0.00000000      -0.00000000      -1.03061673 adf.f=h
 End
Charge 1
End

Engine ADF
  BASIS
   type QZ4P
   core none
  END

  Print FMATSFO
  AllPoints Yes
  FullFock Yes

  Relativity
   level scalar
  End

  SYMMETRY C(3v)

  XC
    gga bp86
    DISPERSION Grimme3 BJDAMP
  END

  NumericalQuality excellent


  SCF
    Iterations 1
  End

  EPRINT
  SFO EIG OVL 
  end
 
  fragments
    $MON1  $MON1.results/adf.rkf
    $MON2  $MON2.results/adf.rkf
  end

EndEngine

END INPUT
eor

# Rename the output file.

cp $COMP.results/ams.rkf $SLURM_SUBMIT_DIR/$COMP.ams.rkf
cp $COMP.results/adf.rkf $SLURM_SUBMIT_DIR/$COMP.adf.rkf
cp $COMP.results/ams.log $SLURM_SUBMIT_DIR/$COMP.log
rm -rf $TMPDIR/$USER/*
