#!/bin/sh

# dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing/CoordinationBondFeCO4CH4/FeCO4CH4.CH4 FeCO4CH4.CH4.results/adf.rkf CH4.rkf
# dependency: /Users/yumanhordijk/PhD/TheoCheM_stack/calculations/PyOrb_testing/CoordinationBondFeCO4CH4/FeCO4CH4.FeCO4 FeCO4CH4.FeCO4.results/adf.rkf FeCO4.rkf

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 2.301146 -0.404537 1.226102 region=CH4 adf.f=CH4
        H 3.111131 -0.340096 0.495832 region=CH4 adf.f=CH4
        H 2.396206 -1.345462 1.772865 region=CH4 adf.f=CH4
        H 2.397203 0.422978 1.930882 region=CH4 adf.f=CH4
        H 1.347844 -1.059512 0.169919 region=CH4 adf.f=CH4
        Fe 0.340889 0.01304 0.460471 region=FeCO4 adf.f=FeCO4
        O -1.750761 -0.800804 -1.376254 region=FeCO4 adf.f=FeCO4
        C -0.923355 -0.47288 -0.642541 region=FeCO4 adf.f=FeCO4
        O -0.498256 2.418317 1.902306 region=FeCO4 adf.f=FeCO4
        O 1.699179 1.483481 -1.657219 region=FeCO4 adf.f=FeCO4
        O -0.6314689999999999 -1.83766 2.490884 region=FeCO4 adf.f=FeCO4
        C -0.263527 -1.094183 1.693249 region=FeCO4 adf.f=FeCO4
        C 1.149179 0.916937 -0.820015 region=FeCO4 adf.f=FeCO4
        C -0.160941 1.470307 1.339834 region=FeCO4 adf.f=FeCO4
    End
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
         6 1 1.0
         6 5 1.0
         6 8 1.0
         6 12 1.0
         6 13 1.0
         6 14 1.0
         7 8 2.0
         9 14 2.0
         10 13 2.0
         11 12 2.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    Fragments
        CH4 CH4.rkf 
        FeCO4 FeCO4.rkf 
    End
    
    XC
        GGA BLYP
    End
    NumericalQuality VeryGood
EndEngine
eor

