#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 2.301146 -0.404537 1.226102 region=CH4
        H 3.111131 -0.340096 0.495832 region=CH4
        H 2.396206 -1.345462 1.772865 region=CH4
        H 2.397203 0.422978 1.930882 region=CH4
        H 1.347844 -1.059512 0.169919 region=CH4
    End
    Symmetrize Yes
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title CH4 fragment
    NumericalQuality VeryGood
EndEngine
eor

