#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        H 0.51193035 0.88668938 -0.1002525 region=H3
        H -1.02386071 -0.0 -0.1002525 region=H3
        H 0.51193035 -0.88668938 -0.1002525 region=H3
    End
    Symmetrize Yes
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    SpinPolarization -3
    XC
        GGA OLYP
    End
    Title H3 fragment
    Unrestricted Yes
    NumericalQuality Good
EndEngine
eor

