#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 0.0 -0.0 0.3007575 region=C adf.f=C
        H 0.51193035 0.88668938 -0.1002525 region=H3 adf.f=H3
        H -1.02386071 -0.0 -0.1002525 region=H3 adf.f=H3
        H 0.51193035 -0.88668938 -0.1002525 region=H3 adf.f=H3
    End
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    SpinPolarization 1
    Fragments
        C ${SCM_ROOT}/Users/yumanhordijk/PhD/Programs/TheoCheM/PyFMO/calculations/PyOrb_testing_2022/HomolyticEthaneMethyl/Methyl.C.results/adf.rkf
        H3 ${SCM_ROOT}/Users/yumanhordijk/PhD/Programs/TheoCheM/PyFMO/calculations/PyOrb_testing_2022/HomolyticEthaneMethyl/Methyl.H3.results/adf.rkf
    End
    Print SFOSITEENERGIES
    XC
        GGA OLYP
    End
    Symmetry C(3V)
    Unrestricted Yes
    NumericalQuality Good
    UnrestrictedFragments Yes
EndEngine
eor

# dependency: /Users/yumanhordijk/PhD/Programs/TheoCheM/PyFMO/calculations/PyOrb_testing_2022/HomolyticEthaneMethyl/Methyl.C -
# dependency: /Users/yumanhordijk/PhD/Programs/TheoCheM/PyFMO/calculations/PyOrb_testing_2022/HomolyticEthaneMethyl/Methyl.H3 -
