#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        N 0.036641 -0.07530199999999999 0.0 region=Cytosine
        C -0.537157 1.142912 0.0 region=Cytosine
        C -1.973458 1.301624 0.0 region=Cytosine
        C -2.727482 0.170004 0.0 region=Cytosine
        N -2.125085 -1.054943 0.0 region=Cytosine
        C -0.712318 -1.211915 0.0 region=Cytosine
        N 0.271406 2.212494 0.0 region=Cytosine
        H -2.434912 2.282696 0.0 region=Cytosine
        H -3.81337 0.179669 0.0 region=Cytosine
        H -2.666246 -1.913322 0.0 region=Cytosine
        O -0.247379 -2.363613 0.0 region=Cytosine
        H -0.127368 3.141263 0.0 region=Cytosine
        H 1.312781 2.100342 0.0 region=Cytosine
    End
    Symmetrize Yes
    BondOrders
         1 2 2.0
         1 6 1.0
         2 3 1.0
         2 7 1.0
         3 4 2.0
         3 8 1.0
         4 5 1.0
         4 9 1.0
         5 6 1.0
         5 10 1.0
         6 11 2.0
         7 12 1.0
         7 13 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title Cytosine fragment
    NumericalQuality VeryGood
EndEngine
eor

