#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        N 6.895847 -0.589089 0.0 region=Guanine
        N 2.928848 -0.3735 0.0 region=Guanine
        C 3.640923 0.852424 0.0 region=Guanine
        C 5.055913 0.633791 0.0 region=Guanine
        C 5.519416 -0.696573 0.0 region=Guanine
        N 4.807474 -1.844049 0.0 region=Guanine
        H 8.222562 1.127841 0.0 region=Guanine
        O 3.016707 1.933757 0.0 region=Guanine
        N 2.635991 -2.685136 0.0 region=Guanine
        H 3.046607 -3.608016 0.0 region=Guanine
        H 1.61449 -2.573989 0.0 region=Guanine
        H 7.543875 -1.36806 0.0 region=Guanine
        H 1.89127 -0.289241 0.0 region=Guanine
        C 3.490481 -1.634087 0.0 region=Guanine
        N 6.12296 1.529813 0.0 region=Guanine
        C 7.198664 0.774875 0.0 region=Guanine
    End
    Symmetrize Yes
    BondOrders
         1 5 1.0
         1 12 1.0
         2 3 1.0
         2 13 1.0
         3 4 1.0
         3 8 2.0
         4 5 2.0
         5 6 1.0
         9 10 1.0
         9 11 1.0
         14 2 1.0
         14 6 2.0
         14 9 1.0
         15 4 1.0
         15 16 2.0
         16 1 1.0
         16 7 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title Guanine fragment
    NumericalQuality VeryGood
EndEngine
eor

