#!/bin/bash
#SBATCH -N 1
#SBATCH -t 240:00:00
#SBATCH --ntasks-per-node=16
#SBATCH --partition=tc

echo "== Starting run at $(date)"
echo "== Job ID: ${SLURM_JOBID}"
echo "== Node list: ${SLURM_NODELIST}"
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}"
echo "== Scratch dir. : ${TMPDIR}"

export SCMLICENSE="/cm/shared/licenses/adf/license.txt"
export SCM_TMPDIR=/scratch/${SLURM_JOBID}
. ~/bin/ams2021.104/amsbashrc.sh 
mkdir -p $SCM_TMPDIR


module list


$AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/1.out

Task SinglePoint

System
  Atoms
P       0.00000000       0.00000000       0.00000000
  End
End

Engine ADF
  
  BASIS
     type TZ2P
     core none
  END
  
  SYMMETRY ATOM
  
  SCF
     ITERATIONS 99
     Converge 1.0e-6 
  END
  
  XC
    GGA BP86
  END
  
  NumericalQuality VERYGOOD
ENDEngine

eor

cp ams.results/ams.rkf $SLURM_SUBMIT_DIR/1.ams.rkf
cp ams.results/adf.rkf $SLURM_SUBMIT_DIR/1.adf.rkf
cp ams.results/ams.log $SLURM_SUBMIT_DIR/1.log

rm -r ams.results

$AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/1.out

Task SinglePoint

System
  Atoms
F       0.00000000       0.00000000      -1.74000000
F       0.00000000       0.00000000       1.74000000
F      -1.74000000       0.00000000       0.00000000
F       0.87000000       1.50688420       0.00000000
F       0.87000000      -1.50688420       0.00000000
  End
End

Engine ADF
  
  BASIS
     type TZ2P
     core none
  END
  
  SYMMETRY D(3H)
  
  SCF
     ITERATIONS 99
     Converge 1.0e-6 
  END
  
  XC
    GGA BP86
  END
 
  NumericalQuality VERYGOOD
ENDEngine

eor

cp ams.results/ams.rkf $SLURM_SUBMIT_DIR/2.ams.rkf
cp ams.results/adf.rkf $SLURM_SUBMIT_DIR/2.adf.rkf
cp ams.results/ams.log $SLURM_SUBMIT_DIR/2.log

rm -r ams.results

$AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

Task SinglePoint

System
  ATOMS
P       0.00000000       0.00000000       0.00000000 f=1
F       0.00000000       0.00000000      -1.74000000 f=2
F       0.00000000       0.00000000       1.74000000 f=2
F      -1.74000000       0.00000000       0.00000000 f=2
F       0.87000000       1.50688420       0.00000000 f=2
F       0.87000000      -1.50688420       0.00000000 f=2
  END
End


Engine ADF
  FRAGMENTS
   1 $SLURM_SUBMIT_DIR/1.adf.rkf
   2 $SLURM_SUBMIT_DIR/2.adf.rkf
  END 

  EPRINT
    SFO Eig Ovl
  END 

  BASIS
     type TZ2P
     core none
  END
  
  SYMMETRY D(3H)
  
  SCF
     ITERATIONS 99
     Converge 1.0e-6 
  END
  
  XC
    GGA BP86
  END
 
  NumericalQuality VERYGOOD
ENDEngine

eor

cp ams.results/ams.rkf $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.ams.rkf
cp ams.results/adf.rkf $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.adf.rkf
cp ams.results/ams.log $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.log

rm -r ams.results
