#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        Al 0.0 0.0 0.0 
        Cl 1.02959589 -1.7833124 0.0 
        Cl 1.02959589 1.7833124 0.0 
        Cl -2.05919178 0.0 0.0 
    End
    BondOrders
         1 2 1.305043578147888
         1 3 1.30518102645874
         1 4 1.305413126945496
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        GGA OLYP
    End
print ekin fmatsfo
EndEngine
eor
