#!/bin/sh

"$ADFBIN/adf" <<eor
    Atoms
    1 O      -0.030933000000       0.173098000000      -2.906776000000    
    2 C      -0.022738000000       0.125460000000      -1.754801000000    
    End
    Basis
        Type TZ2P
        Core None
        CreateOutput None
    End
    GUIBonds
        1 1 2 2.0
    End
    NoPrint LOGFILE
    ALLOW  FRACTIONAL
    XC
        GGA BLYP
    End
    Title CO fragment
    Relativistic Scalar ZORA
    NumericalQuality VeryGood

eor


