#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        F 0.0 1.65588919 0.0 region=F6
        F 0.0 0.0 1.65588919 region=F6
        F 0.0 -1.65588919 0.0 region=F6
        F 1.65588919 0.0 0.0 region=F6
        F 0.0 0.0 -1.65588919 region=F6
        F -1.65588919 0.0 0.0 region=F6
    End
    Symmetrize Yes
    Charge -6
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        GGA OLYP
    End
    Title F6 fragment
    NumericalQuality Good
EndEngine
eor

