#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        C 0.45591372 -0.35534185 0.0 region=left
        N 1.64972303 0.2982665 0.0 region=left
        C 2.92542527 -0.42065198 0.0 region=left
        O 0.36526417 -1.58613512 0.0 region=left
        H 3.00940445 -1.05845681 -0.88711101 region=left
        H 3.00940445 -1.05845681 0.88711101 region=left
        H 1.65543907 1.31098166 0.0 region=left
        H 3.73869444 0.30909289 0.0 region=left
    End
    Symmetrize Yes
    BondOrders
         1 2 1.0
         1 4 2.0
         2 3 1.0
         2 7 1.0
         3 5 1.0
         3 6 1.0
         3 8 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    SpinPolarization 1
    XC
        GGA BLYP
    End
    Title left fragment
    Unrestricted Yes
EndEngine
eor

