name: Package distributions

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: "publishing"
  cancel-in-progress: true

jobs:
  distribution:
    strategy:
      matrix:
        target: [ "windows-latest", "macos-latest"]
        
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase
      - name: Set app version
        run: |
          sed 's/$APPVERSION/0.2.0/' pyproject.toml | diff -p pyproject.toml /dev/stdin | patch 
      - name: Build the app
        run: |
          briefcase build -r
      - name: Package the app
        run: |
          briefcase package --adhoc-sign
      - name: Upload app
        # Briefcase cannot create iOS artefacts; instead, apps
        # must be packaged and published for iOS through Xcode.
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ matrix.target }}
          path: dist
          if-no-files-found: error
      - name: Upload distributions to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: dist/*{.msi,.dmg}
          tag: ${{ github.ref }}
          overwrite: true
